version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      POSTGRES_DB: "${DEKART_POSTGRES_DB}"
  adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080
  cloudsql:
    build: ./cloud_sql_proxy
    ports:
      - "5432:5432"
    profiles:
      - cloudsql
    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      INSTANCE_CONNECTION_NAME: "${INSTANCE_CONNECTION_NAME}"


