version: "3.9"
services:
  db:
    image: postgres:15
    profiles:
      - local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      POSTGRES_DB: "${DEKART_POSTGRES_DB}"
  adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080
  cloudsql:
    build: ./cloud_sql_proxy
    ports:
      - "5432:5432"
    profiles:
      - cloudsql
    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      INSTANCE_CONNECTION_NAME: "${INSTANCE_CONNECTION_NAME}"
  dekart-cloud:
    image: europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-d288d16
    platform: linux/amd64
    mem_limit: 512m
    ports:
      - 8080:8080
    profiles:
      - cloud
    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    environment:
      DEKART_POSTGRES_DB: "${DEKART_POSTGRES_DB}"
      DEKART_POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      DEKART_POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      DEKART_POSTGRES_PORT: "5432"
      DEKART_POSTGRES_HOST: "host.docker.internal"
      DEKART_CLOUD_STORAGE_BUCKET: "${DEKART_CLOUD_STORAGE_BUCKET}"
      DEKART_BIGQUERY_PROJECT_ID: "${DEKART_BIGQUERY_PROJECT_ID}"
      DEKART_BIGQUERY_MAX_BYTES_BILLED: "53687091200"
      DEKART_MAPBOX_TOKEN: "${DEKART_MAPBOX_TOKEN}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      DEKART_CORS_ORIGIN: "${DEKART_CORS_ORIGIN}"
      DEKART_LOG_DEBUG: "${DEKART_LOG_DEBUG}"
      DEKART_LOG_PRETTY: "${DEKART_LOG_PRETTY}"
      DEKART_PORT: "${DEKART_PORT}"
      DEKART_STATIC_FILES: "${DEKART_STATIC_FILES}"
      DEKART_ALLOW_FILE_UPLOAD: "${DEKART_ALLOW_FILE_UPLOAD}"
      DEKART_REQUIRE_GOOGLE_OAUTH: "${DEKART_REQUIRE_GOOGLE_OAUTH}"
      DEKART_GOOGLE_OAUTH_CLIENT_ID: "${DEKART_GOOGLE_OAUTH_CLIENT_ID}"
      DEKART_GOOGLE_OAUTH_SECRET: "${DEKART_GOOGLE_OAUTH_SECRET}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_PRICE_ID: "${STRIPE_PRICE_ID}"
      STRIPE_PRICE_ID_GROW: "${STRIPE_PRICE_ID_GROW}"
      STRIPE_PRICE_ID_MAX: "${STRIPE_PRICE_ID_MAX}"
      DEKART_CLOUD_PUBLIC_STORAGE_BUCKET: "${DEKART_CLOUD_PUBLIC_STORAGE_BUCKET}"
      DEKART_DATA_ENCRYPTION_KEY: "${DEKART_DATA_ENCRYPTION_KEY}"
      DEKART_UX_HOMEPAGE: "${DEKART_UX_HOMEPAGE}"
      DEKART_STORAGE: "${DEKART_STORAGE}"
      DEKART_DATASOURCE: "${DEKART_DATASOURCE}"


