version: "3.9"
services:
  db:
    image: postgres
    profiles:
      - local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      POSTGRES_DB: "${DEKART_POSTGRES_DB}"
  adminer:
    image: adminer
    profiles:
      - local
    restart: always
    ports:
      - 8081:8080
  cloudsql:
    build: ./cloud_sql_proxy
    ports:
      - "5432:5432"
    profiles:
      - cloudsql
    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      INSTANCE_CONNECTION_NAME: "${INSTANCE_CONNECTION_NAME}"
  dekart-cloud:
    image: europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-e9f8018
    platform: linux/amd64
    restart: always
    ports:
      - 8080:8080
    profiles:
      - bigquery
    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    environment:
      DEKART_POSTGRES_DB: "${DEKART_POSTGRES_DB}"
      DEKART_POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      DEKART_POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      DEKART_POSTGRES_PORT: "5432"
      DEKART_POSTGRES_HOST: "host.docker.internal"
      DEKART_CLOUD_STORAGE_BUCKET: "${DEKART_CLOUD_STORAGE_BUCKET}"
      DEKART_BIGQUERY_PROJECT_ID: "${DEKART_BIGQUERY_PROJECT_ID}"
      DEKART_BIGQUERY_MAX_BYTES_BILLED: "53687091200"
      DEKART_MAPBOX_TOKEN: "${DEKART_MAPBOX_TOKEN}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      DEKART_CORS_ORIGIN: "${DEKART_CORS_ORIGIN}"
  # docker compose --env-file .env.snowflake-s3 --profile dekart-oss-snowflake-s3 up
  dekart-oss-snowflake-s3:
    image: dekartxyz/dekart:0.17
    platform: linux/amd64
    restart: always
    ports:
      - 8080:8080
    profiles:
      - snowflake-s3
    environment:
      DEKART_POSTGRES_DB: "${DEKART_POSTGRES_DB}"
      DEKART_POSTGRES_USER: "${DEKART_POSTGRES_USER}"
      DEKART_POSTGRES_PASSWORD: "${DEKART_POSTGRES_PASSWORD}"
      DEKART_POSTGRES_PORT: "5432"
      DEKART_POSTGRES_HOST: "host.docker.internal"
      DEKART_MAPBOX_TOKEN: "${DEKART_MAPBOX_TOKEN}"
      DEKART_STORAGE: "${DEKART_STORAGE}"
      DEKART_DATASOURCE: "${DEKART_DATASOURCE}"
      DEKART_CLOUD_STORAGE_BUCKET: "${DEKART_CLOUD_STORAGE_BUCKET}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      DEKART_ALLOW_FILE_UPLOAD: "${DEKART_ALLOW_FILE_UPLOAD}"
      DEKART_SNOWFLAKE_ACCOUNT_ID: "${DEKART_SNOWFLAKE_ACCOUNT_ID}"
      DEKART_SNOWFLAKE_USER: "${DEKART_SNOWFLAKE_USER}"
      DEKART_SNOWFLAKE_PASSWORD: "${DEKART_SNOWFLAKE_PASSWORD}"
      DEKART_DEV_CLAIMS_EMAIL: "${DEKART_DEV_CLAIMS_EMAIL}"
      DEKART_REQUIRE_AMAZON_OIDC: "${DEKART_REQUIRE_AMAZON_OIDC}"



