name: Dekart Build (cloud + default)

on:
  workflow_call:
    inputs:
      build_app:
        type: boolean
        default: false
      build_e2e:
        type: boolean
        default: false
    outputs:
      app_image:
        description: 'Full tag of the app image (if built)'
        value: ${{ jobs.build.outputs.app_image }}
      e2e_image:
        description: 'Full tag of the e2e image (if built)'
        value: ${{ jobs.build.outputs.e2e_image }}

env:
  DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET != '' &&
                     vars.DEPLOY_TARGET ||
                     (contains(github.repository, 'dekart-cloud') && 'cloud' || 'default') }}
  IMAGE_CACHE_KEY: e2etest-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_image: ${{ steps.set_tags.outputs.app }}
      e2e_image: ${{ steps.set_tags.outputs.e2e }}

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - name: Decide registry / tags
      id: set_tags
      run: |
        if [ "${{ env.DEPLOY_TARGET }}" = "cloud" ]; then
          echo "REGISTRY_BASE=europe-west3-docker.pkg.dev/dekart-cloud/dekart" >> $GITHUB_ENV
          echo "LOGIN=cloud"                                               >> $GITHUB_ENV
        else
          echo "REGISTRY_BASE=ghcr.io/${{ github.repository }}"            >> $GITHUB_ENV
          echo "LOGIN=ghcr"                                                >> $GITHUB_ENV
        fi

        echo "APP=${REGISTRY_BASE}/dekart:sha-${GITHUB_SHA::7}"            >> $GITHUB_OUTPUT
        echo "E2E=${REGISTRY_BASE}/dekart:${IMAGE_CACHE_KEY}"              >> $GITHUB_OUTPUT
      shell: bash

    - name: Authenticate to GCP
      if: env.LOGIN == 'cloud'
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: dekart-cloud
        service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
        export_default_credentials: true
    - run: gcloud auth configure-docker europe-west3-docker.pkg.dev
      if: env.LOGIN == 'cloud'

    - name: Login to GHCR
      if: env.LOGIN == 'ghcr'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create .npmrc
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
        echo "@dekart-xyz:registry=https://npm.pkg.github.com"             >> .npmrc

    - name: Build & push APP image
      if: inputs.build_app
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.set_tags.outputs.app }}
        cache-from: type=registry,ref=${{ env.REGISTRY_BASE }}/dekart:buildcache
        cache-to:   type=registry,ref=${{ env.REGISTRY_BASE }}/dekart:buildcache,mode=max

    - name: Build & push E2E image
      if: inputs.build_e2e
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        target: e2etest
        tags:  ${{ steps.set_tags.outputs.e2e }}
        cache-from: type=registry,ref=${{ env.REGISTRY_BASE }}/dekart:buildcache
        cache-to:   type=registry,ref=${{ env.REGISTRY_BASE }}/dekart:buildcache,mode=max
