name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    if: startsWith(github.head_ref, 'release') != true
    permissions:
      pull-requests: read
      contents: read
  node_tests:
    needs: changes
    if: needs.changes.outputs.js == 'true'
    uses: ./.github/workflows/node_test.yaml
    secrets: inherit
  go_tests:
    needs: changes
    if: needs.changes.outputs.go == 'true'
    uses: ./.github/workflows/go_test.yaml
    secrets: inherit
  e2e_tests:
    needs: changes
    uses: ./.github/workflows/e2e.yaml
    if: needs.changes.outputs.e2e == 'true' && github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
