name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    with:
      build_e2e: true
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  pulumi_preview:
    uses: ./.github/workflows/pulumi_preview.yaml
    secrets: inherit
  e2e_tests:
    needs: [build]
    uses: ./.github/workflows/e2e.yaml
    if: github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
