name: pulumi_preview

on: [workflow_call]


jobs:
  pulumi_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
          project_id: dekart-cloud
          export_default_credentials: true
      - name: pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          cloud-url: gs://dekart-cloud-pulumi
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          # as it is a preview, the image digest does not matter
          IMAGE_DIGEST: does-not-matter
