
name: Push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    with:
      build_app: true
      build_e2e: true
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  e2e_tests:
    needs: [build]
    uses: ./.github/workflows/e2e.yaml
    secrets: inherit
  pulumi_preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA::7})"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
          project_id: dekart-cloud
          export_default_credentials: true
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev
      - name: Pull Docker image
        run: docker pull europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }}
      - name: Get image digest
        id: get_digest
        run: |
          digest=$(docker image inspect europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }} --format='{{index .RepoDigests 0}}')
          echo "::set-output name=digest::$digest"
      - name: pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          cloud-url: gs://dekart-cloud-pulumi
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          IMAGE_DIGEST: ${{ steps.get_digest.outputs.digest }}
