
name: Push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    with:
      build_app: true
      build_e2e: true
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  e2e_tests:
    needs: [build]
    uses: ./.github/workflows/e2e.yaml
    secrets: inherit
  pulumi_preview:
    uses: ./.github/workflows/pulumi_preview.yaml
    secrets: inherit
