name: Push to main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  flavour:
    uses: ./.github/workflows/flavour.yaml

  node_tests:
    needs: [changes]
    uses: ./.github/workflows/node_test.yaml
    secrets: inherit

  go_tests:
    needs: [changes]
    uses: ./.github/workflows/go_test.yaml
    secrets: inherit

  build_e2e:
    needs: [changes, flavour]
    with:
      build_e2e: true
      target: ${{ needs.flavour.outputs.target }}
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  e2e_tests:
    needs: [build_e2e, changes]
    uses: ./.github/workflows/e2e.yaml
    with:
      target: ${{ needs.flavour.outputs.target }}
    permissions:
      contents: read
      packages: write
    secrets: inherit
