
name: Build and Push

on:
  push:
    branches:
      - main
      - cloud-deployment # for testing

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    permissions:
      contents: read
      pull-requests: read
  build:
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
          project_id: dekart-cloud
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:buildcache
          cache-to: type=registry,ref=europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:buildcache,mode=max
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  e2e_tests:
    needs: [changes, build]
    uses: ./.github/workflows/e2e.yaml
    if: needs.changes.outputs.e2e == 'true'
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA::7})"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
          project_id: dekart-cloud
          export_default_credentials: true
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev
      - name: Pull Docker image
        run: docker pull europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }}
      - name: Get image digest
        id: get_digest
        run: |
          digest=$(docker image inspect europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }} --format='{{index .RepoDigests 0}}')
          echo "::set-output name=digest::$digest"
      - name: pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          cloud-url: gs://dekart-cloud-pulumi
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          IMAGE_DIGEST: ${{ steps.get_digest.outputs.digest }}
