name: Release – Premium

on:
  push:
    tags: ['**']

env:
  # Detect flavour once
  DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET != '' &&
                     vars.DEPLOY_TARGET ||
                     (contains(github.repository, 'dekart-cloud') && 'cloud' || 'default') }}

jobs:
  node_tests:
    if: env.DEPLOY_TARGET != 'cloud'
    uses: ./.github/workflows/node_test.yaml
    secrets: inherit

  go_tests:
    if: env.DEPLOY_TARGET != 'cloud'
    uses: ./.github/workflows/go_test.yaml
    secrets: inherit

  build_e2e:
    if: env.DEPLOY_TARGET != 'cloud'
    needs: [node_tests, go_tests]
    with:
      build_e2e: true
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  e2e_tests:
    if: env.DEPLOY_TARGET != 'cloud'
    needs: [node_tests, go_tests, build_e2e]
    uses: ./.github/workflows/e2e.yaml
    secrets: inherit

  docker:
    if: env.DEPLOY_TARGET != 'cloud'
    needs: [node_tests, go_tests, e2e_tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/dekart
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr

      - run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/dekart:buildcache
          cache-to:   type=registry,ref=ghcr.io/${{ github.repository }}/dekart:buildcache,mode=max
