name: Release – Cloud

on:
  release:
    types: [published]   # → runs when a GitHub Release is published

jobs:
  flavour:
    uses: ./.github/workflows/flavour.yaml      # tiny helper, outputs is_cloud

  deploy:
    if: needs.flavour.outputs.is_cloud == 'true'
    needs: [flavour]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.21' }

      - id: short_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: dekart-cloud
          service_account_key: ${{ secrets.PRIVATE_GITHUB_ACTIONS_DEKART_CLOUD }}
          export_default_credentials: true
      - run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - run: docker pull europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }}
      - id: digest
        run: |
          echo "digest=$(docker image inspect europe-west3-docker.pkg.dev/dekart-cloud/dekart/dekart:sha-${{ steps.short_sha.outputs.sha }} --format='{{index .RepoDigests 0}}')" >> $GITHUB_OUTPUT

      - uses: pulumi/actions@v5
        with:
          command: up
          cloud-url: gs://dekart-cloud-pulumi
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          IMAGE_DIGEST:            ${{ steps.digest.outputs.digest }}
          VERSION_ID:              ${{ github.event.release.tag_name }}
